[Account 1080] dependencies upgrade + test standalone vue
PrestaShopCorp/prestashop_accounts_vue_components pull request #136
Opened 2022-01-10 16:26 UTC by antoinemetifeu

# Dependencies upgrade

* zoid not updated : The parent & child version should be the same
* sass & sass-loader : I forgot the reason...
* @vue/cli-plugin-eslint : beta version but watch for next upgrade
* @storybook/vue & @storybook/theming & @storybook/addons & @storybook/addon-docs & @storybook/addon-actions : Updated but already a new version is out (just run npx sb upgrade and try if all build works)
* @storybook/addon-knobs : must be replaced by @storybook/addon-controls

# Test standalone vue

Another alternative to CDC or webcomponents.

2022-01-31 10:36 UTC, aAmorim27 requested changes
We have a regression when trying to access the associated shops page on a multishop context where some shops aren't linked yet
There is also a problem with the prestakit the background has turned white and some parts of the BO interface are broken
![image](https://user-images.githubusercontent.com/46534068/151778765-a99e3863-4281-40c8-80ff-ebfbb9436509.png)

2022-01-31 10:36 UTC, aAmorim27 commented on src/components/panel/accountSubComponents/AccountLinkToUi.vue
> -      },
We have a regression here, we can't access the shops page from the "View my associated shops" button 
i think that during a merge we lost a part of the function code
You can fix that by adding these lines
```js
openLinkShopModal(action = 'associate') {
      this.action = action;
      this.trackAssociateOrManageAccountButton();

      this.cdcUiDisplayed = true;
    },
``

2022-02-01 08:47 UTC, antoinemetifeu commented
> We have a regression when trying to access the associated shops page on a multishop context where some shops aren't linked yet ~~There is also a problem with the prestakit the background has turned white and some parts of the BO interface are broken~~ ![image](https://user-images.githubusercontent.com/46534068/151778765-a99e3863-4281-40c8-80ff-ebfbb9436509.png)

Hello, can I have more explanation on the problem and how to reproduce it?

2022-02-01 08:52 UTC, aAmorim27 commented
> > We have a regression when trying to access the associated shops page on a multishop context where some shops aren't linked yet ~There is also a problem with the prestakit the background has turned white and some parts of the BO interface are broken~ ![image](https://user-images.githubusercontent.com/46534068/151778765-a99e3863-4281-40c8-80ff-ebfbb9436509.png)
> 
> Hello, can I have more explanation on the problem and how to reproduce it?

You need to be in a all shops context on a multishop store
- Link the first store but not the others
- Click on the dropdown and click in the "View my associated shops" item
- You will be redirected to the link shop page instead of the shops page

2022-02-01 08:57 UTC, antoinemetifeu commented on src/components/PsAccounts.vue
> +  },
I will pass all in composition API into ACCOUNT-1105 ticket (the 'context' lib must be a composable to be fully compatible)

2022-02-01 08:58 UTC, antoinemetifeu commented
> > > We have a regression when trying to access the associated shops page on a multishop context where some shops aren't linked yet ~There is also a problem with the prestakit the background has turned white and some parts of the BO interface are broken~ ![image](https://user-images.githubusercontent.com/46534068/151778765-a99e3863-4281-40c8-80ff-ebfbb9436509.png)
> > 
> > 
> > Hello, can I have more explanation on the problem and how to reproduce it?
> 
> You need to be in a all shops context on a multishop store
> 
> * Link the first store but not the others
> * Click on the dropdown and click in the "View my associated shops" item
> * You will be redirected to the link shop page instead of the shops page

I will retry but it's certainly fixed by https://github.com/PrestaShopCorp/prestashop_accounts_vue_components/pull/136#discussion_r795538039

2022-02-02 16:49 UTC, aAmorim27 approved these changes

2022-02-21 13:52 UTC, antoinemetifeu commented
- Metged into #140

2022-02-21 13:52 UTC, closed without merging