feat: responsive panel account
PrestaShopCorp/prestashop_accounts_vue_components pull request #190
Opened 2023-09-22 16:06 UTC by ClaraLpresta

# 📚 Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue) / [ACCOUNT-XXXX](https://forge.prestashop.com/browse/ACCOUNT-XXXX)
Sync w/ PRs:

## ❓ Type of change

Please delete options that are not relevant.

- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] 📦 New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 📖 Documentation (updates to the documentation or readme)

## 📝 Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have made corresponding changes for storybook

2023-09-25 08:10 UTC, aAmorim27 requested changes
Thx for the work :+1: 
Just some minor changes to do to have the same render as the Figma and we can merge this PR

2023-09-25 08:10 UTC, aAmorim27 commented on src/components/panel/accountSubComponents/AccountLinkToUi.vue
When i display the component on a screen size under 768px the two buttons aren't taking all the horizontal space like in the Figma 
![image](https://github.com/PrestaShopCorp/prestashop_accounts_vue_components/assets/46534068/66d48b84-9cba-448e-9f35-e7a3ef707b20)
Maybe you could add a `acc-w-1/2 md:acc-w-auto` class for each button and increase the spacing between them to `32px` to have the same render as the Figma ?

2023-09-26 12:28 UTC, atourneriePresta approved these changes

2023-09-26 12:28 UTC, merged

2023-10-02 08:18 UTC, ClaraLpresta commented on src/components/panel/accountSubComponents/AccountLinkToUi.vue
Sorry for the error, thanks for the correction !